importing spandsp snapshot 20090714

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -463,7 +463,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS SPANDSP_LT_CURRENT SPANDSP_LT_REVISION SPANDSP_LT_AGE INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar build build_cpu build_vendor build_os host host_cpu host_vendor host_os CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CPP EGREP SED LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB DSYMUTIL ac_ct_DSYMUTIL NMEDIT ac_ct_NMEDIT CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL LIBOBJS COND_DOC_TRUE COND_DOC_FALSE COND_TESTS_TRUE COND_TESTS_FALSE COND_TESTDATA_TRUE COND_TESTDATA_FALSE COND_MMX_TRUE COND_MMX_FALSE COND_SSE_TRUE COND_SSE_FALSE COND_SSE2_TRUE COND_SSE2_FALSE COND_SSE3_TRUE COND_SSE3_FALSE COND_SSE4_1_TRUE COND_SSE4_1_FALSE COND_SSE4_2_TRUE COND_SSE4_2_FALSE COND_SSE4A_TRUE COND_SSE4A_FALSE COND_SSE5_TRUE COND_SSE5_FALSE CC_FOR_BUILD CPPFLAGS_FOR_BUILD COMP_VENDOR_CFLAGS COMP_VENDOR_LDFLAGS SIMLIBS TESTLIBS SPANDSP_USE_FIXED_POINT SPANDSP_MISALIGNED_ACCESS_FAILS SPANDSP_USE_EXPORT_CAPABILITY INSERT_INTTYPES_HEADER INSERT_STDINT_HEADER INSERT_TGMATH_HEADER INSERT_MATH_HEADER LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS SPANDSP_LT_CURRENT SPANDSP_LT_REVISION SPANDSP_LT_AGE INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar build build_cpu build_vendor build_os host host_cpu host_vendor host_os CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CPP EGREP SED LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB DSYMUTIL ac_ct_DSYMUTIL NMEDIT ac_ct_NMEDIT CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL LIBOBJS COND_DOC_TRUE COND_DOC_FALSE COND_TESTS_TRUE COND_TESTS_FALSE COND_TESTDATA_TRUE COND_TESTDATA_FALSE COND_MMX_TRUE COND_MMX_FALSE COND_SSE_TRUE COND_SSE_FALSE COND_SSE2_TRUE COND_SSE2_FALSE COND_SSE3_TRUE COND_SSE3_FALSE COND_SSSE3_TRUE COND_SSSE3_FALSE COND_SSE4_1_TRUE COND_SSE4_1_FALSE COND_SSE4_2_TRUE COND_SSE4_2_FALSE COND_SSE4A_TRUE COND_SSE4A_FALSE COND_SSE5_TRUE COND_SSE5_FALSE CC_FOR_BUILD CPPFLAGS_FOR_BUILD COMP_VENDOR_CFLAGS COMP_VENDOR_LDFLAGS SIMLIBS TESTLIBS SPANDSP_USE_FIXED_POINT SPANDSP_MISALIGNED_ACCESS_FAILS SPANDSP_USE_EXPORT_CAPABILITY INSERT_INTTYPES_HEADER INSERT_STDINT_HEADER INSERT_TGMATH_HEADER INSERT_MATH_HEADER LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1039,6 +1039,7 @@ Optional Features:
   --enable-sse         Enable SSE support
   --enable-sse2        Enable SSE2 support
   --enable-sse3        Enable SSE3 support
+  --enable-ssse3       Enable SSSE3 support
   --enable-sse4-1      Enable SSE4.1 support
   --enable-sse4-2      Enable SSE4.2 support
   --enable-sse4a       Enable SSE4A support
@@ -4623,7 +4624,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4626 "configure"' > conftest.$ac_ext
+  echo '#line 4627 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -5535,7 +5536,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:5538:" \
+echo "$as_me:5539:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -6884,11 +6885,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6887: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6888: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6891: \$? = $ac_status" >&5
+   echo "$as_me:6892: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7174,11 +7175,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7177: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7178: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7181: \$? = $ac_status" >&5
+   echo "$as_me:7182: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7278,11 +7279,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7281: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7282: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:7285: \$? = $ac_status" >&5
+   echo "$as_me:7286: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -9681,7 +9682,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9684 "configure"
+#line 9685 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -9781,7 +9782,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9784 "configure"
+#line 9785 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12186,11 +12187,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12189: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12190: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12193: \$? = $ac_status" >&5
+   echo "$as_me:12194: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -12290,11 +12291,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12293: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12294: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12297: \$? = $ac_status" >&5
+   echo "$as_me:12298: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -13875,11 +13876,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13878: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13879: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13882: \$? = $ac_status" >&5
+   echo "$as_me:13883: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -13979,11 +13980,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13982: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13983: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13986: \$? = $ac_status" >&5
+   echo "$as_me:13987: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16193,11 +16194,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16196: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16197: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16200: \$? = $ac_status" >&5
+   echo "$as_me:16201: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16483,11 +16484,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16486: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16487: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16490: \$? = $ac_status" >&5
+   echo "$as_me:16491: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16587,11 +16588,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16590: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16591: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:16594: \$? = $ac_status" >&5
+   echo "$as_me:16595: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -20706,9 +20707,9 @@ if test "${enable_sse3+set}" = set; then
   enableval="$enable_sse3"
 
 fi;
-# Check whether --enable-sse3 or --disable-sse3 was given.
-if test "${enable_sse3+set}" = set; then
-  enableval="$enable_sse3"
+# Check whether --enable-ssse3 or --disable-ssse3 was given.
+if test "${enable_ssse3+set}" = set; then
+  enableval="$enable_ssse3"
 
 fi;
 # Check whether --enable-sse4_1 or --disable-sse4_1 was given.
@@ -31305,6 +31306,9 @@ gnu)
     if test "$enable_sse4_1" = "yes" ; then
         COMP_VENDOR_CFLAGS="-msse41 $COMP_VENDOR_CFLAGS"
     fi
+    if test "$enable_ssse3" = "yes" ; then
+        COMP_VENDOR_CFLAGS="-mssse3 $COMP_VENDOR_CFLAGS"
+    fi
     if test "$enable_sse3" = "yes" ; then
         COMP_VENDOR_CFLAGS="-msse3 $COMP_VENDOR_CFLAGS"
     fi
@@ -31418,6 +31422,16 @@ if test "$enable_sse3" = yes; then
 else
   COND_SSE3_TRUE='#'
   COND_SSE3_FALSE=
+fi
+
+
+
+if test "$enable_ssse3" = yes; then
+  COND_SSSE3_TRUE=
+  COND_SSSE3_FALSE='#'
+else
+  COND_SSSE3_TRUE='#'
+  COND_SSSE3_FALSE=
 fi
 
 
@@ -31570,6 +31584,14 @@ if test "$enable_sse4_1" = "yes" ; then
 
 cat >>confdefs.h <<\_ACEOF
 #define SPANDSP_USE_SSE4_1 1
+_ACEOF
+
+    enable_ssse3="yes"
+fi
+if test "$enable_ssse3" = "yes" ; then
+
+cat >>confdefs.h <<\_ACEOF
+#define SPANDSP_USE_SSSE3 1
 _ACEOF
 
     enable_sse3="yes"
@@ -31790,6 +31812,13 @@ if test -z "${COND_SSE3_TRUE}" && test -z "${COND_SSE3_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"COND_SSE3\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"COND_SSE3\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${COND_SSSE3_TRUE}" && test -z "${COND_SSSE3_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"COND_SSSE3\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"COND_SSSE3\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -32455,6 +32484,8 @@ s,@COND_SSE2_TRUE@,$COND_SSE2_TRUE,;t t
 s,@COND_SSE2_FALSE@,$COND_SSE2_FALSE,;t t
 s,@COND_SSE3_TRUE@,$COND_SSE3_TRUE,;t t
 s,@COND_SSE3_FALSE@,$COND_SSE3_FALSE,;t t
+s,@COND_SSSE3_TRUE@,$COND_SSSE3_TRUE,;t t
+s,@COND_SSSE3_FALSE@,$COND_SSSE3_FALSE,;t t
 s,@COND_SSE4_1_TRUE@,$COND_SSE4_1_TRUE,;t t
 s,@COND_SSE4_1_FALSE@,$COND_SSE4_1_FALSE,;t t
 s,@COND_SSE4_2_TRUE@,$COND_SSE4_2_TRUE,;t t
