importing spandsp 0.0.2pre17

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -463,7 +463,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CPP EGREP build build_cpu build_vendor build_os host host_cpu host_vendor host_os LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL LIBOBJS COND_DOC_TRUE COND_DOC_FALSE COND_TESTS_TRUE COND_TESTS_FALSE COND_ITUTESTS_TRUE COND_ITUTESTS_FALSE TESTLIBS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS SPANDSP_LT_CURRENT SPANDSP_LT_REVISION SPANDSP_LT_AGE INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CPP EGREP build build_cpu build_vendor build_os host host_cpu host_vendor host_os LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL LIBOBJS COND_DOC_TRUE COND_DOC_FALSE COND_TESTS_TRUE COND_TESTS_FALSE COND_ITUTESTS_TRUE COND_ITUTESTS_FALSE TESTLIBS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1498,6 +1498,22 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
 
+SPANDSP_MAJOR_VERSION=0
+SPANDSP_MINOR_VERSION=0
+SPANDSP_MICRO_VERSION=2
+
+SPANDSP_LT_CURRENT=0
+SPANDSP_LT_REVISION=1
+SPANDSP_LT_AGE=0
+
+VERSION=$SPANDSP_MAJOR_VERSION.$SPANDSP_MINOR_VERSION.$SPANDSP_MICRO_VERSION
+PACKAGE=spandsp
+
+
+
+
+
+
 ac_aux_dir=
 for ac_dir in config $srcdir/config; do
   if test -f $ac_dir/install-sh; then
@@ -1798,8 +1814,8 @@ fi
 
 
 # Define the identity of the package.
- PACKAGE=spandsp
- VERSION=0.0.2
+ PACKAGE=$PACKAGE
+ VERSION=$VERSION
 
 
 cat >>confdefs.h <<_ACEOF
@@ -4377,7 +4393,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4380 "configure"' > conftest.$ac_ext
+  echo '#line 4396 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -5250,7 +5266,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:5253:" \
+echo "$as_me:5269:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -6284,11 +6300,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6287: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6303: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6291: \$? = $ac_status" >&5
+   echo "$as_me:6307: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -6517,11 +6533,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6520: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6536: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6524: \$? = $ac_status" >&5
+   echo "$as_me:6540: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -6577,11 +6593,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6580: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6596: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:6584: \$? = $ac_status" >&5
+   echo "$as_me:6600: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -7911,7 +7927,7 @@ linux*)
   libsuff=
   case "$host_cpu" in
   x86_64*|s390x*|powerpc64*)
-    echo '#line 7914 "configure"' > conftest.$ac_ext
+    echo '#line 7930 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -8782,7 +8798,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 8785 "configure"
+#line 8801 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -8880,7 +8896,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 8883 "configure"
+#line 8899 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11059,11 +11075,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11062: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11078: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:11066: \$? = $ac_status" >&5
+   echo "$as_me:11082: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -11119,11 +11135,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11122: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11138: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:11126: \$? = $ac_status" >&5
+   echo "$as_me:11142: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -11630,7 +11646,7 @@ linux*)
   libsuff=
   case "$host_cpu" in
   x86_64*|s390x*|powerpc64*)
-    echo '#line 11633 "configure"' > conftest.$ac_ext
+    echo '#line 11649 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -12501,7 +12517,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12504 "configure"
+#line 12520 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12599,7 +12615,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12602 "configure"
+#line 12618 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13426,11 +13442,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13429: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13445: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13433: \$? = $ac_status" >&5
+   echo "$as_me:13449: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -13486,11 +13502,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13489: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13505: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13493: \$? = $ac_status" >&5
+   echo "$as_me:13509: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14800,7 +14816,7 @@ linux*)
   libsuff=
   case "$host_cpu" in
   x86_64*|s390x*|powerpc64*)
-    echo '#line 14803 "configure"' > conftest.$ac_ext
+    echo '#line 14819 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -15541,11 +15557,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15544: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15560: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15548: \$? = $ac_status" >&5
+   echo "$as_me:15564: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -15774,11 +15790,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15777: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15793: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15781: \$? = $ac_status" >&5
+   echo "$as_me:15797: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -15834,11 +15850,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15837: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15853: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:15841: \$? = $ac_status" >&5
+   echo "$as_me:15857: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -17168,7 +17184,7 @@ linux*)
   libsuff=
   case "$host_cpu" in
   x86_64*|s390x*|powerpc64*)
-    echo '#line 17171 "configure"' > conftest.$ac_ext
+    echo '#line 17187 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -18039,7 +18055,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 18042 "configure"
+#line 18058 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -18137,7 +18153,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 18140 "configure"
+#line 18156 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -19470,6 +19486,22 @@ cat >>confdefs.h <<_ACEOF
 _ACEOF
 
 
+
+# Check whether --enable-doc or --disable-doc was given.
+if test "${enable_doc+set}" = set; then
+  enableval="$enable_doc"
+
+fi;
+# Check whether --enable-tests or --disable-tests was given.
+if test "${enable_tests+set}" = set; then
+  enableval="$enable_tests"
+
+fi;
+# Check whether --enable-itutests or --disable-itutests was given.
+if test "${enable_itutests+set}" = set; then
+  enableval="$enable_itutests"
+
+fi;
 
 echo "$as_me:$LINENO: checking for error_at_line" >&5
 echo $ECHO_N "checking for error_at_line... $ECHO_C" >&6
@@ -26056,7 +26088,6 @@ done
 
 
 # Checks for libraries.
-#AC_CHECK_LIB([tiff], [TIFFOpen],,echo "Can't work without libtiff"; exit 1)
 
 echo "$as_me:$LINENO: checking for TIFFOpen in -ltiff" >&5
 echo $ECHO_N "checking for TIFFOpen in -ltiff... $ECHO_C" >&6
@@ -26064,7 +26095,7 @@ if test "${ac_cv_lib_tiff_TIFFOpen+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   ac_check_lib_save_LIBS=$LIBS
-LIBS="-ltiff  $LIBS"
+LIBS="-ltiff -lm $LIBS"
 cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
@@ -26129,6 +26160,8 @@ _ACEOF
 
   LIBS="-ltiff $LIBS"
 
+else
+  echo "Can't build without libtiff"; exit 1
 fi
 
 
@@ -26273,7 +26306,8 @@ if test $ac_cv_lib_xml2_xmlParseFile = yes; then
   TESTLIBS="$TESTLIBS -lxml2"
 fi
 
-echo "$as_me:$LINENO: checking for afOpenFile in -laudiofile" >&5
+if test -n "$enable_tests" ; then
+    echo "$as_me:$LINENO: checking for afOpenFile in -laudiofile" >&5
 echo $ECHO_N "checking for afOpenFile in -laudiofile... $ECHO_C" >&6
 if test "${ac_cv_lib_audiofile_afOpenFile+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -26339,9 +26373,11 @@ echo "$as_me:$LINENO: result: $ac_cv_lib_audiofile_afOpenFile" >&5
 echo "${ECHO_T}$ac_cv_lib_audiofile_afOpenFile" >&6
 if test $ac_cv_lib_audiofile_afOpenFile = yes; then
   TESTLIBS="$TESTLIBS -laudiofile"
+else
+  echo "Can't make tests without libaudiofile"; exit 1
 fi
 
-echo "$as_me:$LINENO: checking for fftw_plan_dft_1d in -lfftw3" >&5
+    echo "$as_me:$LINENO: checking for fftw_plan_dft_1d in -lfftw3" >&5
 echo $ECHO_N "checking for fftw_plan_dft_1d in -lfftw3... $ECHO_C" >&6
 if test "${ac_cv_lib_fftw3_fftw_plan_dft_1d+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -26409,7 +26445,7 @@ if test $ac_cv_lib_fftw3_fftw_plan_dft_1d = yes; then
   TESTLIBS="$TESTLIBS -lfftw3"
 fi
 
-echo "$as_me:$LINENO: checking for fftw_create_plan in -lfftw" >&5
+    echo "$as_me:$LINENO: checking for fftw_create_plan in -lfftw" >&5
 echo $ECHO_N "checking for fftw_create_plan in -lfftw... $ECHO_C" >&6
 if test "${ac_cv_lib_fftw_fftw_create_plan+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -26477,7 +26513,7 @@ if test $ac_cv_lib_fftw_fftw_create_plan = yes; then
   TESTLIBS="$TESTLIBS -lfftw"
 fi
 
-echo "$as_me:$LINENO: checking for pthread_attr_init in -lpthread" >&5
+    echo "$as_me:$LINENO: checking for pthread_attr_init in -lpthread" >&5
 echo $ECHO_N "checking for pthread_attr_init in -lpthread... $ECHO_C" >&6
 if test "${ac_cv_lib_pthread_pthread_attr_init+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -26545,7 +26581,7 @@ if test $ac_cv_lib_pthread_pthread_attr_init = yes; then
   TESTLIBS="$TESTLIBS -lpthread"
 fi
 
-echo "$as_me:$LINENO: checking for dlopen in -ldl" >&5
+    echo "$as_me:$LINENO: checking for dlopen in -ldl" >&5
 echo $ECHO_N "checking for dlopen in -ldl... $ECHO_C" >&6
 if test "${ac_cv_lib_dl_dlopen+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -26613,13 +26649,13 @@ if test $ac_cv_lib_dl_dlopen = yes; then
   TESTLIBS="$TESTLIBS -ldl"
 fi
 
-echo "$as_me:$LINENO: checking for uc_start in -lunicall" >&5
+    echo "$as_me:$LINENO: checking for uc_start in -lunicall" >&5
 echo $ECHO_N "checking for uc_start in -lunicall... $ECHO_C" >&6
 if test "${ac_cv_lib_unicall_uc_start+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   ac_check_lib_save_LIBS=$LIBS
-LIBS="-lunicall  $LIBS"
+LIBS="-lunicall -ltiff -ldl $LIBS"
 cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
@@ -26681,22 +26717,7 @@ if test $ac_cv_lib_unicall_uc_start = yes; then
   TESTLIBS="$TESTLIBS -lunicall"
 fi
 
-
-# Check whether --enable-doc or --disable-doc was given.
-if test "${enable_doc+set}" = set; then
-  enableval="$enable_doc"
-
-fi;
-# Check whether --enable-tests or --disable-tests was given.
-if test "${enable_tests+set}" = set; then
-  enableval="$enable_tests"
-
-fi;
-# Check whether --enable-itutests or --disable-itutests was given.
-if test "${enable_itutests+set}" = set; then
-  enableval="$enable_itutests"
-
-fi;
+fi
 
 
 
@@ -27405,6 +27426,9 @@ s,@ECHO_C@,$ECHO_C,;t t
 s,@ECHO_N@,$ECHO_N,;t t
 s,@ECHO_T@,$ECHO_T,;t t
 s,@LIBS@,$LIBS,;t t
+s,@SPANDSP_LT_CURRENT@,$SPANDSP_LT_CURRENT,;t t
+s,@SPANDSP_LT_REVISION@,$SPANDSP_LT_REVISION,;t t
+s,@SPANDSP_LT_AGE@,$SPANDSP_LT_AGE,;t t
 s,@INSTALL_PROGRAM@,$INSTALL_PROGRAM,;t t
 s,@INSTALL_SCRIPT@,$INSTALL_SCRIPT,;t t
 s,@INSTALL_DATA@,$INSTALL_DATA,;t t
diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -14,15 +14,31 @@
 # along with this program; if not, write to the Free Software
 # Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 #
-# $Id: configure.in,v 1.14 2005/01/16 10:52:01 steveu Exp $
+# $Id: configure.in,v 1.15 2005/01/28 23:30:48 steveu Exp $
 
 # @start 1
 
 AC_INIT
+
+SPANDSP_MAJOR_VERSION=0
+SPANDSP_MINOR_VERSION=0
+SPANDSP_MICRO_VERSION=2
+
+SPANDSP_LT_CURRENT=0
+SPANDSP_LT_REVISION=1
+SPANDSP_LT_AGE=0
+
+VERSION=$SPANDSP_MAJOR_VERSION.$SPANDSP_MINOR_VERSION.$SPANDSP_MICRO_VERSION
+PACKAGE=spandsp
+
+AC_SUBST(SPANDSP_LT_CURRENT)
+AC_SUBST(SPANDSP_LT_REVISION)
+AC_SUBST(SPANDSP_LT_AGE)
+
 AC_CONFIG_SRCDIR([src/tone_generate.c])
 AC_CONFIG_AUX_DIR(config)
 AC_CONFIG_HEADERS([src/config.h:config-h.in])
-AM_INIT_AUTOMAKE(spandsp, 0.0.2)
+AM_INIT_AUTOMAKE($PACKAGE, $VERSION)
 
 AC_PROG_CC
 AC_PROG_CXX
@@ -36,6 +52,10 @@ AC_C_INLINE
 AC_C_VOLATILE
 
 AC_TYPE_SIGNAL
+
+AC_ARG_ENABLE(doc,     [  --enable-doc      Build the documentation])
+AC_ARG_ENABLE(tests,   [  --enable-tests    Build the test programs])
+AC_ARG_ENABLE(itutests,[  --enable-itutests Build TIFF test files for some ITU test images])
 
 AC_FUNC_ERROR_AT_LINE
 AC_FUNC_VPRINTF
@@ -91,20 +111,17 @@ AC_CHECK_HEADERS(FL/Fl_Cartesian.H, LIBS="$LIBS -lfltk_cartesian -lfltk -lsupc++
 AC_CHECK_HEADERS(X11/X.h, TESTLIBS="$TESTLIBS -L/usr/X11R6/lib -lXft -lXext -lX11")
 
 # Checks for libraries.
-#AC_CHECK_LIB([tiff], [TIFFOpen],,echo "Can't work without libtiff"; exit 1)
-AC_CHECK_LIB([tiff], [TIFFOpen])
+AC_CHECK_LIB([tiff], [TIFFOpen],,echo "Can't build without libtiff"; exit 1, -lm)
 AC_CHECK_LIB([m], [cos])
 AC_CHECK_LIB([xml2], [xmlParseFile], TESTLIBS="$TESTLIBS -lxml2")
-AC_CHECK_LIB([audiofile], [afOpenFile], TESTLIBS="$TESTLIBS -laudiofile")
-AC_CHECK_LIB([fftw3], [fftw_plan_dft_1d], TESTLIBS="$TESTLIBS -lfftw3")
-AC_CHECK_LIB([fftw], [fftw_create_plan], TESTLIBS="$TESTLIBS -lfftw")
-AC_CHECK_LIB([pthread], [pthread_attr_init], TESTLIBS="$TESTLIBS -lpthread")
-AC_CHECK_LIB([dl], [dlopen], TESTLIBS="$TESTLIBS -ldl")
-AC_CHECK_LIB([unicall], [uc_start], TESTLIBS="$TESTLIBS -lunicall")
-
-AC_ARG_ENABLE(doc,     [  --enable-doc      Build the documentation])
-AC_ARG_ENABLE(tests,   [  --enable-tests    Build the test programs])
-AC_ARG_ENABLE(itutests,[  --enable-itutests Build TIFF test files for some ITU test images])
+if test -n "$enable_tests" ; then
+    AC_CHECK_LIB([audiofile], [afOpenFile], TESTLIBS="$TESTLIBS -laudiofile",echo "Can't make tests without libaudiofile"; exit 1)
+    AC_CHECK_LIB([fftw3], [fftw_plan_dft_1d], TESTLIBS="$TESTLIBS -lfftw3")
+    AC_CHECK_LIB([fftw], [fftw_create_plan], TESTLIBS="$TESTLIBS -lfftw")
+    AC_CHECK_LIB([pthread], [pthread_attr_init], TESTLIBS="$TESTLIBS -lpthread")
+    AC_CHECK_LIB([dl], [dlopen], TESTLIBS="$TESTLIBS -ldl")
+    AC_CHECK_LIB([unicall], [uc_start], TESTLIBS="$TESTLIBS -lunicall",, -ltiff -ldl)
+fi
 
 AM_CONDITIONAL([COND_DOC], [test "$enable_doc" = yes])
 AM_CONDITIONAL([COND_TESTS], [test "$enable_tests" = yes])
