importing spandsp snapshot 20090530

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -25900,7 +25900,7 @@ fi
 done
 
 
-for ac_header in audiofile.h
+for ac_header in sndfile.h
 do
 as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
 if eval "test \"\${$as_ac_Header+set}\" = set"; then
@@ -30294,13 +30294,13 @@ ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
 ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
 ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
-    echo "$as_me:$LINENO: checking for afOpenFile in -laudiofile" >&5
-echo $ECHO_N "checking for afOpenFile in -laudiofile... $ECHO_C" >&6
-if test "${ac_cv_lib_audiofile_afOpenFile+set}" = set; then
+    echo "$as_me:$LINENO: checking for sf_open in -lsndfile" >&5
+echo $ECHO_N "checking for sf_open in -lsndfile... $ECHO_C" >&6
+if test "${ac_cv_lib_sndfile_sf_open+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   ac_check_lib_save_LIBS=$LIBS
-LIBS="-laudiofile  $LIBS"
+LIBS="-lsndfile  $LIBS"
 cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
@@ -30314,11 +30314,11 @@ extern "C"
 #endif
 /* We use char because int might match the return type of a gcc2
    builtin and then its argument prototype would still apply.  */
-char afOpenFile ();
+char sf_open ();
 int
 main ()
 {
-afOpenFile ();
+sf_open ();
   ;
   return 0;
 }
@@ -30345,24 +30345,24 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-  ac_cv_lib_audiofile_afOpenFile=yes
+  ac_cv_lib_sndfile_sf_open=yes
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
-ac_cv_lib_audiofile_afOpenFile=no
+ac_cv_lib_sndfile_sf_open=no
 fi
 rm -f conftest.err conftest.$ac_objext \
       conftest$ac_exeext conftest.$ac_ext
 LIBS=$ac_check_lib_save_LIBS
 fi
-echo "$as_me:$LINENO: result: $ac_cv_lib_audiofile_afOpenFile" >&5
-echo "${ECHO_T}$ac_cv_lib_audiofile_afOpenFile" >&6
-if test $ac_cv_lib_audiofile_afOpenFile = yes; then
-  SIMLIBS="$SIMLIBS -laudiofile"
+echo "$as_me:$LINENO: result: $ac_cv_lib_sndfile_sf_open" >&5
+echo "${ECHO_T}$ac_cv_lib_sndfile_sf_open" >&6
+if test $ac_cv_lib_sndfile_sf_open = yes; then
+  SIMLIBS="$SIMLIBS -lsndfile"
 else
-  { { echo "$as_me:$LINENO: error: \"Can't make tests without libaudiofile (does your system require a libaudiofile-devel package?)\"" >&5
-echo "$as_me: error: \"Can't make tests without libaudiofile (does your system require a libaudiofile-devel package?)\"" >&2;}
+  { { echo "$as_me:$LINENO: error: \"Can't make tests without libsndfile (does your system require a libsndfile-devel package?)\"" >&5
+echo "$as_me: error: \"Can't make tests without libsndfile (does your system require a libsndfile-devel package?)\"" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
